# Automatically generates an artifact, which is a zip file containing the icon.png, the manifest.json, the LICENSE.md, and the README.md files. The artifact is uploaded to the GitHub Actions artifacts page.
name: Generate Package
on:
    push:
        branches:
          - main
    pull_request:
        branches:
          - main

jobs:
    checkversionmismatch:
        runs-on: ubuntu-latest
        name: Validate Unified Version
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Read manifest.json
            id: manifest
            uses: juliangruber/read-file-action@v1
            with:
                path: manifest.json
          - name: Extract version from manifest.json
            id: version
            run: |
                echo "::set-output name=version::${{ fromJSON(steps.manifest.outputs.content).version }}"
          - name: Read SelectAnyNumber.csproj Version
            id: csproj
            uses: mavrosxristoforos/get-xml-info@1.1.1
            with:
                xml-file: SelectAnyNumber.csproj
                xpath: /Project/PropertyGroup/Version
          - name: Validate version
            run: |
                if [ "${{ steps.version.outputs.version }}" != "${{ steps.csproj.outputs.value }}" ]; then
                    echo "Version mismatch between manifest.json and SelectAnyNumber.csproj"
                    exit 1
                fi
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Setup .NET Core SDK
            uses: actions/setup-dotnet@v3
            with:
                dotnet-version: 7.0.104
          - name: Build Dotnet
            run: dotnet build --configuration Release
          - name: Copy File to Mod Folder
            run: |
                mkdir -p SelectAnyNumber/BepInEx/plugins
                cp -r bin/Release/netstandard2.0/PickAnyNumber.dll SelectAnyNumber/BepInEx/plugins
          - name: Upload Artifact
            uses: actions/upload-artifact@v3
            with:
                name: package
                path: |
                    icon.png
                    manifest.json
                    LICENSE.md
                    README.md
                    SelectAnyNumber
